name: Buld and Deploy

on: 
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: NPM Install
        run: npm install
        
      - name: NPM Build
        run: npm run build

      - name: Set up 404 Page
        run: cp dist/gym-lessons-angular-application/browser/index.html dist/gym-lessons-angular-application/browser/404.html
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/gym-lessons-angular-application/browser
